# Ansible
ANSIBLE_HOME=${HOME}/.local/share/ansible
ANSIBLE_CONFIG=${HOME}/.config/ansible/ansible.cfg
# Gradle
GRADLE_USER_HOME=${HOME}/.local/share/gradle
# NPM
NPM_CONFIG_USERCONFIG=${HOME}/.config/npm/.npmrc
